apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: gateway-service
  name: gateway-service
  namespace: spring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: gateway-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: gateway-service
    spec:
      containers:
      - image: miclip/gateway-service:0.0.11
        imagePullPolicy: IfNotPresent
        name: gateway-service
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: gateway-service
  name: gateway-service
  namespace: spring
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30160
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: gateway-service
  sessionAffinity: None
  type: NodePort
