spring:
  application:
    name: second-service
server:
  port: 80

eureka:
  instance:
    hostname: second-service
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
